/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ModuloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Notebook
 */
public class TelaPromocoes extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaPromocoes
     */
    public TelaPromocoes() {
        initComponents();
        conexao = ModuloConexao.conector();

    }
//pesquisar veículos pelo nome com filtro

    private void pesquisarveiculos() {
        String sql = "select * from tbveiculos where modelo like ?";
        try {
            pst = conexao.prepareStatement(sql);

            pst.setString(1, txtModelo.getText() + "%");
            rs = pst.executeQuery();

            tblVeiculos.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
// metodo para settar os campos do formulario com  o conteudo da tabela

    public void setarcampos() {
        int setar = tblVeiculos.getSelectedRow();
        txtModelo.setText((String) tblVeiculos.getModel().getValueAt(setar, 1));
        txtFabricante.setText((String) tblVeiculos.getModel().getValueAt(setar, 2));
        txtCor.setText((String) tblVeiculos.getModel().getValueAt(setar, 3));
        txtAno.setText((String) tblVeiculos.getModel().getValueAt(setar, 4));
        txtPreco.setText((String) tblVeiculos.getModel().getValueAt(setar, 5));
        txtChassi.setText((String) tblVeiculos.getModel().getValueAt(setar, 6));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVeiculos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JLabel1 = new javax.swing.JLabel();
        JLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtFabricante = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        txtChassi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(null);

        tblVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVeiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVeiculos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 60, 514, 91);

        jLabel1.setText("Pesquisar Veículo:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(111, 16, 86, 14);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(201, 13, 201, 20);

        jLabel2.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        jLabel2.setText("Cadastrar Promoção:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 300, 203, 31);

        JLabel1.setText("Modelo:");
        getContentPane().add(JLabel1);
        JLabel1.setBounds(30, 170, 38, 14);

        JLabel2.setText("Fabricante:");
        getContentPane().add(JLabel2);
        JLabel2.setBounds(30, 220, 55, 14);

        jLabel3.setText("Cor:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 270, 21, 14);

        jLabel4.setText("Ano:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 170, 23, 14);

        jLabel5.setText("Preço:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 220, 31, 14);

        jLabel6.setText("Chassi:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 270, 35, 14);
        getContentPane().add(txtModelo);
        txtModelo.setBounds(90, 170, 114, 20);
        getContentPane().add(txtFabricante);
        txtFabricante.setBounds(90, 220, 115, 20);
        getContentPane().add(txtCor);
        txtCor.setBounds(90, 260, 115, 20);
        getContentPane().add(txtAno);
        txtAno.setBounds(320, 170, 120, 20);
        getContentPane().add(txtPreco);
        txtPreco.setBounds(320, 210, 120, 20);

        txtChassi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChassiActionPerformed(evt);
            }
        });
        getContentPane().add(txtChassi);
        txtChassi.setBounds(320, 260, 120, 20);

        jLabel8.setText("Taxa Percentual de Desconto:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 340, 145, 14);

        jLabel9.setText("Data Limite da Promoção:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 380, 122, 14);

        btnCadastrar.setText("Cadastrar");
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(440, 390, 81, 23);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 340, 145, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(210, 380, 150, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/9.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 600, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtChassiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChassiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChassiActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
// o evento abaixo é do tipo em tempo real
        pesquisarveiculos();
    }//GEN-LAST:event_jTextField1KeyReleased

    private void tblVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVeiculosMouseClicked

        // TODO add your handling code here:
            setarcampos();
    }//GEN-LAST:event_tblVeiculosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private javax.swing.JLabel JLabel2;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tblVeiculos;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtChassi;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
